library identifier: 'custom-lib@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'git@https://github.com/mkthakral/jenkins-gy.git'])

node{
    stage('StopHybris') {
        stopHybris(
            environment: ${environment}
        ) 
    }
    
}